myrpc:
  client:
    global:
      registry:
        name: zookeeper
        url: 127.0.0.1:2181
      serializer:
        name: fst
      loadBalance:
        name: random
      cluster:
        name: failOver
    instances:
      user-service:
        loadBalance:
          name: roundRobin

server:
  port: 8080